version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install conan
    - conan install . --install-folder build

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf_rtd.py